import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, Headphones, Watch, Cable, ShieldCheck, MessageCircle, Truck } from "lucide-react";
import { ScrollReveal } from "./ScrollReveal";
export function HomeExperience(){return <section className="container-custom studio-section">
 <ScrollReveal><div className="studio-section-heading"><div><p className="studio-eyebrow">02 / MORE THAN A PHONE</p><h2>Make it<br/><span>your everyday.</span></h2></div><p className="studio-description">The little things that complete your setup.<br/>Explore the Apple ecosystem.</p></div></ScrollReveal>
 <div className="studio-bento"><ScrollReveal className="studio-bento-large"><Link href="/showroom" className="studio-showroom"><Image src="/showroom/showroom-main-apple-flag.jpg" alt="Inside the Theekzu Mobile showroom" fill sizes="(max-width:767px) 90vw, 55vw" className="object-cover"/><div><span className="studio-eyebrow">MEET THEEKZU</span><h3>Real people.<br/>A real passion for Apple.</h3><span className="studio-text-link">Inside our showroom <ArrowUpRight size={20}/></span></div></Link></ScrollReveal>
 <div className="studio-accessories">{[{icon:Headphones,title:'Sound, upgraded.',label:'AirPods & audio',url:'/accessories?sub=airpods'},{icon:Watch,title:'Every moment counts.',label:'Apple Watch',url:'/accessories?sub=apple-watch'},{icon:Cable,title:'Stay connected.',label:'Chargers & accessories',url:'/accessories'}].map(({icon:Icon,title,label,url},i)=><ScrollReveal key={title} delay={i*70}><Link href={url} className="studio-accessory"><Icon size={37} strokeWidth={1}/><div><span>{label}</span><h3>{title}</h3></div><ArrowUpRight size={20}/></Link></ScrollReveal>)}</div></div>
 <div className="studio-promises">{[{icon:ShieldCheck,title:'Carefully checked.',text:'Device condition and details, explained before you buy.'},{icon:MessageCircle,title:'A real conversation.',text:'Get personal advice and availability on WhatsApp.'},{icon:Truck,title:'Across Sri Lanka.',text:'Ask our team about delivery to your doorstep.'}].map(({icon:Icon,title,text})=><div key={title}><Icon size={24} strokeWidth={1.3}/><h3>{title}</h3><p>{text}</p></div>)}</div>
 </section>}
